{{- if not .Values.backend.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "s3sentinel.fullname" . }}-backend
  labels:
    {{- include "s3sentinel.labels" . | nindent 4 }}
type: Opaque
stringData:
  accessKey: {{ .Values.backend.accessKey | quote }}
  secretKey: {{ .Values.backend.secretKey | quote }}
{{- end }}
{{- if and (include "s3sentinel.stsEnabled" .) (not .Values.sts.existingSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "s3sentinel.fullname" . }}-sts
  labels:
    {{- include "s3sentinel.labels" . | nindent 4 }}
type: Opaque
stringData:
  tokenSecret: {{ .Values.sts.tokenSecret | quote }}
{{- end }}
